apiVersion: v1
data:
  DI_COMPLETED_PARTITIONS: "10"
  DI_ERROR_PARTITIONS: "10"
  DI_INCOMING_EDIFACT_RECORD_PARSED_PARTITIONS: "10"
  DI_INCOMING_MARC_BIB_FOR_ORDER_PARSED_PARTITIONS: "10"
  DI_INCOMING_MARC_BIB_RECORD_PARSED_PARTITIONS: "10"
  DI_INITIALIZATION_STARTED_PARTITIONS: "10"
  DI_INVENTORY_AUTHORITY_CREATED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_INVENTORY_AUTHORITY_UPDATED_PARTITIONS: "10"
  DI_INVENTORY_AUTHORITY_UPDATED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_INVENTORY_HOLDINGS_CREATED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_INVENTORY_HOLDING_CREATED_PARTITIONS: "10"
  DI_INVENTORY_HOLDING_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_HOLDING_NOT_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_HOLDING_UPDATED_PARTITIONS: "10"
  DI_INVENTORY_INSTANCE_CREATED_PARTITIONS: "10"
  DI_INVENTORY_INSTANCE_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_INSTANCE_NOT_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_INSTANCE_UPDATED_PARTITIONS: "10"
  DI_INVENTORY_ITEM_CREATED_PARTITIONS: "10"
  DI_INVENTORY_ITEM_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_ITEM_NOT_MATCHED_PARTITIONS: "10"
  DI_INVENTORY_ITEM_UPDATED_PARTITIONS: "10"
  DI_LOG_SRS_MARC_AUTHORITY_RECORD_CREATED_PARTITIONS: "10"
  DI_LOG_SRS_MARC_AUTHORITY_RECORD_UPDATED_PARTITIONS: "10"
  DI_MARC_FOR_DELETE_RECEIVED_PARTITIONS: "10"
  DI_MARC_FOR_UPDATE_RECEIVED_PARTITIONS: "10"
  DI_PARSED_RECORDS_CHUNK_SAVED_PARTITIONS: "10"
  DI_RAW_RECORDS_CHUNK_PARSED_PARTITIONS: "10"
  DI_RAW_RECORDS_CHUNK_READ_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_CREATED_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_DELETED_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_MATCHED_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_MODIFIED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_NOT_MATCHED_PARTITIONS: "10"
  DI_SRS_MARC_AUTHORITY_RECORD_UPDATED: "10"
  DI_SRS_MARC_BIB_RECORD_MATCHED_PARTITIONS: "10"
  DI_SRS_MARC_BIB_RECORD_MATCHED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_SRS_MARC_BIB_RECORD_MODIFIED_PARTITIONS: "10"
  DI_SRS_MARC_BIB_RECORD_NOT_MATCHED_PARTITIONS: "10"
  DI_SRS_MARC_BIB_RECORD_UPDATED_PARTITIONS: "10"
  DI_SRS_MARC_HOLDINGS_HOLDING_HRID_SET_PARTITIONS: "10"
  DI_SRS_MARC_HOLDINGS_RECORD_CREATED_PARTITIONS: "10"
  DI_SRS_MARC_HOLDINGS_RECORD_MATCHED: "10"
  DI_SRS_MARC_HOLDINGS_RECORD_MODIFIED_READY_FOR_POST_PROCESSING_PARTITIONS: "10"
  DI_SRS_MARC_HOLDINGS_RECORD_NOT_MATCHED: "10"
  DI_SRS_MARC_HOLDINGS_RECORD_UPDATED_PARTITIONS: "10"
kind: ConfigMap
metadata:
  annotations: {}
  name: kafka-topics
  namespace: folio
