apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDiTCCAnGgAwIBAgIRAOzm9UFPn8V0YSbb9kYUO6MwDQYJKoZIhvcNAQELBQAw
    XjEPMA0GA1UEAwwGSzhzIENBMQswCQYDVQQGEwJVUzEPMA0GA1UEBwwGQXVzdGlu
    MQ8wDQYDVQQKDAZPcmFjbGUxDDAKBgNVBAsMA09jaTEOMAwGA1UECAwFVGV4YXMw
    HhcNMjUwNDA3MTM0MTExWhcNMzAwNDA3MTM0MTExWjBeMQ8wDQYDVQQDDAZLOHMg
    Q0ExCzAJBgNVBAYTAlVTMQ8wDQYDVQQHDAZBdXN0aW4xDzANBgNVBAoMBk9yYWNs
    ZTEMMAoGA1UECwwDT2NpMQ4wDAYDVQQIDAVUZXhhczCCASIwDQYJKoZIhvcNAQEB
    BQADggEPADCCAQoCggEBAK8Nai+B4UqL6Y+FPC3U6l6mJBvypghU2SaAn0JqYSmR
    Vbyf+cwNv2ah/btXyTSL0k/vNwtqQYmaM9dA7ko/fgOnADdEWhuG9ReJiyEzeAcX
    BcIBEeqVQ3gpIN1xNDgrZEhXlEm5R02VWA8A4f3t+KJGQv/cHdXLjqkWzMLT6Nw8
    xW2n8YmnGYVDFCkMgKzyYC65Ea7etgHbBJzqVqFCsJHJZmBQZNGI08lmq4otC6vn
    OiC+APeTI5H8PlBy0Nvle+zIfA5+O1dWhtFJOKSC6ztFPgneA62zY4l1QQTHtNsu
    LHmdXJxdsyinHbiYIC4rtXeKlnATFB9Rh+biTa3i1zMCAwEAAaNCMEAwDwYDVR0T
    AQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFN12gHgdYyLd7wbB
    tTlN5OftGIdNMA0GCSqGSIb3DQEBCwUAA4IBAQBLEWnwwg0l2YJAquHi17krn/zG
    POJytwKr8LfdsaqSUnY/F2+pq+1tCka+rqoTCBE+nSPk69GELtVQTBHU0qCH7ZC5
    KMDq2aXCiMTmIfDiSo92ZM9qbgTazjWy6RQzp2/Ewyt5vrNCeoy1hvMjbZ2UmB/c
    Lkx8aiCYUpNa0Y7set84y64xTzf/XcbAnVJ74Racq2iEQIMaXzEwyeDg5KqzxZFy
    MzFRxAhOh2idKcluOwhMUmtPu5FvorFTd9qx+e0gHI2e6M1tVRxKcgijXiVr93lV
    Y0+vc2LBXz3gPX2YYXIXYXNsXFGd+T03ZdwjkJYOSR5dMQjSAhl2eN6OuuH/
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kube-root-ca.crt
  namespace: folio
