apiVersion: v1
data:
  CP_MEMBERS_NUM: Mw==
  HAZELCAST_FILE: L3Vzci9sb2NhbC9iaW4vZm9saW8vb2thcGkvaGF6ZWxjYXN0LnhtbA==
  HAZELCAST_IP: b2thcGk=
  HAZELCAST_PORT: NTcwMQ==
  HAZELCAST_VERTX_PORT: NTcwMg==
  INITDB: ZmFsc2U=
  JAVA_OPTIONS: LVhYOk1heFJBTVBlcmNlbnRhZ2U9NjYuMCAtRHZlcnR4Lm1ldHJpY3Mub3B0aW9ucy5lbmFibGVkPWZhbHNlICAgLURoYXplbGNhc3QuZGlhZ25vc3RpY3MuZW5hYmxlZD10cnVlIC1EaGF6ZWxjYXN0LmxvZ2dpbmcudHlwZT1zbGY0ag==
  KAFKA_HOST: aHR0cDovL2thZmthMi1oZWFkbGVzcy5rYWZrYS1jbHVzdGVyLnN2Yy5jbHVzdGVyLmxvY2Fs
  KAFKA_PORT: OTA5NA==
  NAMESPACE: Zm9saW8=
  OKAPI_CLUSTERHOST: b2thcGk=
  OKAPI_COMMAND: Y2x1c3Rlcg==
  OKAPI_HOST: b2thcGk=
  OKAPI_LOGLEVEL: QUxM
  OKAPI_NODENAME: b2thcGk=
  OKAPI_PORT: OTEzMA==
  OKAPI_STORAGE: cG9zdGdyZXM=
  OKAPI_URL: aHR0cDovL29rYXBp
  PG_DATABASE: b2thcGk=
  PG_HOST: MTkzLjEyMi45MS4xMjQ=
  PG_PASSWORD: Zm9saW8xMjM=
  PG_PORT: NTQzMg==
  PG_USERNAME: Zm9saW8=
  VERTX_OPTS: LUR2ZXJ0eC5vcHRpb25zLm1heEV2ZW50TG9vcEV4ZWN1dGVUaW1lPTQwMDAw
  ZIPKIN_API_URL: aHR0cDovL3ppcGtpbi5pc3Rpby1zeXN0ZW06OTQxMS9hcGkvdjIvc3BhbnM=
  ZIPKIN_TRACING_ENABLED: ZmFsc2U=
kind: Secret
metadata:
  name: okapi-config
  namespace: folio
type: Opaque
